name: Raspberry PI3 RootFS Build

on: push

jobs:
  my-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://dvjhwf8qp/lanbuntu:latest
      with:
        ref: 2018.05
      env:
        br_config: raspberrypi3_lancer_defconfig
    - name: Build
      run: | 
        make "$br_config"
        make
