name: I.MX6 RootFS Build
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          branch: 2014.05
      - uses: docker://docker.pkg.github.com/james-martinez/ubuntu/lanbuntu
        with:
          username: "${{secrets.DOCKER_USERNAME}}"
          password: "${{secrets.DOCKER_TOKEN}}"
      - run: |
          make wandboard_lancer_defconfig 
          make
