name: I.MX6 RootFS Build

on: push

jobs:
  my-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Pull docker image
        uses: docker://dvjhwf8qp/lanbuntu:latest
    - name: Checkout repo
        uses: actions/checkout@v1
        with:
          ref: 2014.05
    - name: Build rootfs
      run: make wandboard_lancer_defconfig
      run: make
