name: I.MX6 RootFS Build
on: push
jobs:
  build:
    runs-on: [ubuntu-16.04]
    container:
      image: dvjhwf8qp/lanbuntu
    steps:
      - uses: actions/checkout@v1
        with:
          branch: 2014.05
      - run: |
          make wandboard_lancer_defconfig 
          make
