name: I.MX6 RootFS Build

on: push


jobs:
  my-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build rootfs
      run: echo "test test"
      uses: docker://dvjhwf8qp/lanbuntu:latest
