name: I.MX6 RootFS Build
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: docker.pkg.github.com/james-martinez/ubuntu/lanbuntu
      env:
        login-server: docker.pkg.github.com
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }}   
    steps:
      - uses: actions/checkout@v1
        with:
          branch: 2014.05
      - run: |
          make wandboard_lancer_defconfig 
          make
