name: I.MX6 RootFS Build
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: dvjhwf8qp/lanbuntu:latest
    steps:
      - run: ls /usr/local/xtools 
      
      #- name: Build rootfs
       # uses: docker://dvjhwf8qp/lanbuntu:latest
       # with:
