name: Raspberry PI3 RootFS Build
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    container:
      image: docker.pkg.github.com/james-martinez/ubuntu/lanbuntu:latest
    steps:
      - uses: actions/checkout@v1
        with:
          branch: 2018.05
      - run: |
          make raspberrypi3_lancer_defconfig
          make
