name: I.MX6 RootFS Build

on: push


jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      uses: docker://alpine:3.8
      run: |
        echo "helli"
