name: I.MX6 RootFS Build
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    container: dvjhwf8qp/lanbuntu
    steps:
      - uses: actions/checkout@v1
        with:
          branch: 2014.05
      - name : Build 
        run: |
          make wandboard_lancer_defconfig 
          make
