name: I.MX6 RootFS Build

on: push

jobs:
  my-job:
    name: Ubuntu
    runs-on: ubuntu-latest
    #container: dvjhwf8qp/lanbuntu:latest
      steps:
      - name: Say Hello
        run: echo "hello"
