name: I.MX6 RootFS Build
on: push
jobs:
  build:
    container:
      image: dvjhwf8qp/lanbuntu:latest
    #steps:
      #- name: Build rootfs
       # uses: docker://dvjhwf8qp/lanbuntu:latest
       # with:
