name: I.MX6 RootFS Build
on: push
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          branch: 2014.05
      - uses: azure/docker-login@v1
          with:
            login-server: docker.pkg.github.com
            username: "${{secrets.DOCKER_USERNAME}}"
            password: "${{secrets.DOCKER_TOKEN}}"
      - uses: docker://docker.pkg.github.com/james-martinez/ubuntu/lanbuntu
      - run: |
          make wandboard_lancer_defconfig 
          make
